//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient.Statistic
{
    internal enum StatsKind
    {
        Metric,
        ServiceCheck,
        Event,
    }
}
