//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient
{
    internal class Serializers
    {
        public MetricSerializer MetricSerializer { get; set; }

        public ServiceCheckSerializer ServiceCheckSerializer { get; set; }

        public EventSerializer EventSerializer { get; set; }
    }
}
