//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
using System;

namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient.Worker
{
    internal interface IManualResetEvent
    {
        bool Wait(TimeSpan duration);

        void Set();

        void Reset();
    }
}
