//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient.Bufferize
{
    internal interface IBufferBuilderHandler
    {
        void Handle(byte[] buffer, int length);
    }
}
