//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient
{
#pragma warning disable CS1591
    internal interface IRandomGenerator
    {
        bool ShouldSend(double sampleRate);
    }
}
