//------------------------------------------------------------------------------
// <auto-generated />
// This file was automatically generated by the UpdateVendors tool.
//------------------------------------------------------------------------------
namespace OpenTelemetry.Instrumentation.Vendors.StatsdClient
{
    internal enum MetricType
    {
        Count,
        Timing,
        Gauge,
        Histogram,
        Distribution,
        Meter,
        Set,
    }
}
